spaceapi-community/spaceapi-server-rs

- Cargo.toml
> Fixed documentation url, bumped version

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/server/mod.rs
- tests/lib.rs
This can be used to stop the server again, by calling the `close()`
method on the `Listening` instance.
Because Iron doesn't re-publish the `Listening` type, we need to add
Hyper as a dependency. See https://github.com/iron/iron/issues/406.
This change allows us to add integration tests that test the server
output.
> Return HttpResult<Listening> from serve()

- CHANGELOG.md
- src/errors.rs
- src/server/mod.rs
- tests/lib.rs
This is much more flexible than allowing just Ipv4Addr and a port.
Since it changes the constructor it's a breaking change.
-  [x] Update changelog
> Use ToSocketAddrs instead of IP port

- src/lib.rs
- src/server/mod.rs
I don't think the macro creates any added value, besides one less mut variable.
This would also solve #19.
> Initialize router without macro

- src/server/mod.rs
Fixes warning:
```
src/server/mod.rs:13:5: 13:26 warning: unused import, #[warn(unused_imports)] on by default
src/server/mod.rs:13 use ::api::SensorTemplate;
^~~~~~~~~~~~~~~~~~~~~
```
> Remove unused import

- Cargo.toml
Previously, building the latest urlencoded (according to semver) would break.
> Update hyper / iron / urlencoded dependencies

- src/lib.rs
Rust 1.9 shows the following warning:
src/lib.rs:18:9: 18:24 warning: extern crate `spaceapi` is private, and cannot be reexported (error E0364), consider declaring with `pub`, #[warn(private_in_public)] on by default
src/lib.rs:18 pub use spaceapi as api;
^~~~~~~~~~~~~~~
src/lib.rs:18:9: 18:24 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
src/lib.rs:18:9: 18:24 note: for more information, see the explanation for E0446 (`--explain E0446`)
> Pub-export spaceapi crate

- src/server/mod.rs
This will help us to debug problems like coredump-ch/status#98 in the future.
> Log redis connection info when starting server

- CHANGELOG.md
- Cargo.toml
- src/errors.rs
- src/lib.rs
- src/sensors.rs
- src/server/handlers.rs
- src/server/mod.rs
- src/types.rs
This is pretty cool :) It gives us a connection pool with 1 to 6 active Redis connections.
We need to depend on a git fork of the r2d2-redis library until [this PR](https://github.com/sorccu/r2d2-redis/pull/8) is merged and released.
If the database dies while the server process is started, the error is handled gracefully (regular output without sensors) + logged.
If all connections are blocked for longer than 1 second (see connection timeout in configuration), the same thing would happen. This means that sensors are not always contained in the response if the database server or the network is overloaded, but I think that's better than slowing down the entire API response for >1 second if a database server is down or overloaded. We could increase the timeout though, if you think it should …
> Integrate connection pooling for redis with r2d2

- Cargo.toml
I don't think we expose any part of r2d2 / redis to the user, so this is not a breaking change.
> Bump redis and r2d2_redis dependencies

- CHANGELOG.md
- Cargo.toml
- examples/simple.rs
- src/lib.rs
- src/modifiers.rs
This will fix #4.
But https://github.com/coredump-ch/spaceapi-rs/pull/31 will need to be merged and published first.
> Version information in API output

- Cargo.toml
We can't actually release 0.3.0 because Cargo.toml contains a star dependency version specifier :dizzy_face: 
I propose to merge this and #54, and then to release 0.3.1.
> Specify clippy version

- .travis.yml
- Cargo.toml
Currently our travis pipeline is more or less useless, since we only build on nighlty which fails, but we ignore the result.
> Fix travis

- .travis.yml
Disable coverall because it is horribly slow (bacause it compiles kcov from scratch...) and we don't really use the results.
> Improve travis CI build times

- .travis.yml
- README.md
Due to a breaking changes in dependencies we need to bump the minimum
tested Rust version to 1.17.0
> Update minimum tested Rust version to 1.17.0

- .travis.yml
- README.md
Due to the move the README had some broken links.
> Fix README and simplify CI

- .travis.yml
- README.md
The unicode-normalization crate requires a newer Rust version.
> Bump minimal required Rust version

- Cargo.toml
- src/errors.rs
- src/lib.rs
- src/sensors.rs
error-type was last updated in 2015 and is not compatible with the 2018 edition.
https://docs.rs/quick-error/1.2.2/quick_error/
> Replace error-type macro with quick-error

- examples/with_custom_redis_pool.rs
- src/server/mod.rs
This patch adds the option to build a SpaceapiServer by initializing it
with an existing r2d2_redis Pool.
I'm not too happy of that big `match` block, but if I use `.unwrap_or_else` it just goes down in `unwrap` hell... Any suggestions?
I still have to add tests, as soon as I understand more about testing with rust 😊
When merged, it should close #84 .
> Init SpaceServer with existing Redis pool

- .circleci/config.yml
- CHANGELOG.md
- README.md
Bump Rust version to 1.36, update MSRV guarantees.
> Bump Rust to 1.36

- src/modifiers.rs
> Fix panic in StateFromPeopleNowPresent modifier

- .circleci/config.yml
- CHANGELOG.md
- Cargo.toml
> Prepare 0.6.0 release

- .circleci/config.yml
The combine crate requires the 'resolver' feature from cargo.
- [na] CHANGELOG updated if applicable
> Bump MSRV to 1.51 and remove cargo audit

- .circleci/config.yml
- CHANGELOG.md
- Cargo.toml
The dependency rustix requires it.
> Bump MSRV to 1.63
