README.md

Added more shields to README

---

.travis.yml

They get annoying quickly and provide no added value.

Remove Travis IRC notifications

---

src/modifiers.rs

This was discussed in #8 but somehow didn't make it before the merge

Remove any trait from StatusModifier

---

src/modifiers.rs

Remove unused Any import

---

AUTHORS.md
Cargo.toml
src/server/handlers.rs

See discussion in coredump-ch/spaceapi-rs#10

Replace .to_string() with .into() everywhere

---

README.md

Add Hint of Usage to Readme

---

README.md
examples/simple.rs

Can be run with `cargo run --example simple`.
Also refs #27.

Add simple example

---

Cargo.toml
examples/with_sensors.rs

Can be run with `cargo run --example with_sensors`

Add example that uses sensors

---

Cargo.toml
src/lib.rs

Also fixes the issues noted in #47

Add support for clippy

---

.travis.yml
Cargo.toml
examples/simple.rs
examples/with_sensors.rs
src/lib.rs
src/modifiers.rs
src/server/handlers.rs
tests/lib.rs

Update spaceapi dependency to use serde

---

Cargo.toml

See http://www.integer32.com/2017/01/20/categories-and-ci-badges.html
for announcement.

Add Travis badge to Cargo.toml

---

Cargo.toml
examples/simple.rs
examples/with_sensors.rs
src/modifiers.rs
src/server/handlers.rs

* Use the ApiBuilder
* Use the Default trait

Simplify examples

---

Cargo.toml
src/modifiers.rs
tests/lib.rs

- Update crate
- Move versions extension to extensions field
- Use StatusBuilder in tests
Fixes #65.

Update spaceapi crate

---

CHANGELOG.md
examples/simple.rs
examples/with_sensors.rs
src/lib.rs
src/sensors.rs
src/server/handlers.rs
src/server/mod.rs
tests/lib.rs

Add SpaceapiServerBuilder

---

examples/simple.rs
src/modifiers.rs
src/server/mod.rs

There is no point in adding the same data to the status over and over
again ;)

Add version info statically

---

Cargo.toml
src/lib.rs
src/server/handlers.rs

We still haven't cleaned up completely since the repository move :wink:

Fix references

---

src/modifiers.rs
src/server/handlers.rs

Resloves #49
I skipped a few of the warnings because it seemed like the code would be far less readable after the suggested changes.

Fix issues found with clippy

---

.circleci/config.yml
src/lib.rs
src/modifiers.rs
src/sensors.rs
src/server/handlers.rs
src/server/mod.rs

Checks formatting with `cargo fmt` during CI. Also fixes all style issues.

Check formatting during CI

---

CHANGELOG.md
Cargo.toml

Update spaceapi crate to 0.7

---

CHANGELOG.md
Cargo.toml
examples/with_custom_redis_pool.rs
src/errors.rs
src/sensors.rs
src/server/mod.rs

Update redis and r2d2 crates

---

.circleci/config.yml
CHANGELOG.md
Cargo.toml

Update redis to 0.15 and r2d2_redis to 0.13

---

CHANGELOG.md
Cargo.toml
README.md
examples/simple.rs
examples/with_custom_redis_pool.rs
examples/with_sensors.rs
src/lib.rs
src/modifiers.rs
tests/lib.rs

Update spaceapi crate to 0.8 to support v14

---

examples/with_custom_redis_pool.rs
src/server/handlers.rs

- [na] CHANGELOG updated if applicable

Fix minor issues

---

.circleci/config.yml

A dependency requires a newer Rust version.
- [na] CHANGELOG updated if applicable

Bump MSRV to 1.56

---

CHANGELOG.md
Cargo.toml
src/server/handlers.rs

Enable 2021 edition and run cargo fix --edition-idioms

---

.circleci/config.yml
CHANGELOG.md
Cargo.toml
src/server/handlers.rs

Update env_logger and redis

---

CHANGELOG.md
Cargo.toml
src/lib.rs

Prepare 0.7.0 release

---

CHANGELOG.md
Cargo.toml
examples/simple.rs
examples/with_custom_redis_pool.rs
examples/with_sensors.rs
src/lib.rs
src/modifiers.rs
src/sensors.rs
src/server/handlers.rs
src/server/mod.rs
tests/lib.rs

Update spaceapi crate to 0.9
